### ISSUE TITLE
Requisition and economy rework

### ISSUE THREAD

**Issue by GalacticChimp** [ZAB909/ChapterMaster#153]
some ideas
- add another currency for heavy industrial works, like Stellaris?
- TODO

duplicates #141, so closing this one

**Comment by Blogaugis** [comment]
A few ideas would be:
Requisition and labor.
Requisition is basically the resource we have now, it shows various materials (ranging from metals, spare parts and rations).
Labor would actually be the capability to convert the requisition into useful equipment, and in general the capability to build stuff.

**Idea**: a techmarine, no equipment, `technology / 10` (to tie up to the RPG stats that we have. In average case, it should be 4 points). a servo arms doubles the amount. `technology * (0.1 * SA)` Servo arms either 1, 2 or perhaps more if artifact/master crafted. 8 points with default equipment.
10 labor points are generated by escort-sized vessel (this shows small, generally damage-control type workshops);
100 labor points are generated by cruiser sized vessel (it is a space-faring town tier);
1000 labor points are generated by Capital ships (a whole city).
Fortress Monastery could also generate 1000 by default, but perhaps we want some customization, development options.

**Usage example**: I think fortifications should require just 100 requisition, but 1000 (or more) labor. So, a single techmarine left on a dead world, would develop the fortification level in 125 turns, if 100 requisition were given.
A bolter would require 5 requisition, but just 1 labor.
A Rhino transport, costing 50 requisition, but requiring 100 labor, would take 13 turns for a single techmarine to build.
Fortress monastery, with 500 requisition, could build 10 Rhinos in 1 turn.
When not on assignment to build, they could instead repair other vehicle (and ship) units, and build housing on imperial worlds, raising population maximum amount and increasing the planetary disposition.

**Other considerations**: controlled planetary population, lairs and other hidden installations.
Chapter traits, that could allow other marines to make use of their tech stat (like crafters, tech-heresy or tech-brothers), while not techmarines (other specialists, like apothecaries, or even average marines using shovels to dig trenches).
Distributing works across techmarines (and other labor-capable units).
Experience gained from participating in construction.
Different resource types.

**Comment by KRdaMystic** [comment]
### Resource/Crafting change

**Current System**
REQ


**_Ideas/Concept_**
REQ,ADA,CER,TM

**Tech marines**: Crafters/Maintainers/Salvagers, will be less numerous for chapters without crafters or tech bros.
**Servitors**: Fodder Maintainers/Salvagers meant to augment a TM 2-6 can be managed to assist TM depending on skill
**REQ**: Buying gear/requesting favors
**ADA**: Crafting res. for Master-crafted/Artificer/Rare equip and expensive vehicles (Adamantium)
**CER**: Crafting res. for Vehicles/EQ when cut off from AM or without purchasing with req (Ceramite)

### Acquisition
Requisition: Gathered through remaining in good standing and assisting the sector entities (Currency)
Adamantine: Rare ruin drop, Heavy≥Battles, small supply (Rare)
Ceramite: Salvaged from destroyed Vehs allied & enemy (Scavs get more),Can be purch from admech in bulk. (Cheap)

When renegade could be raided from forge worlds with varying rewards dependent on difficulty

### Affecters
**-Advantages:** 
-Crafters: Better MW/Rare/Arti gear, Chance to use less res on a craft proj. Marines have better TECH score on recruitment

-Tech bros. :More TMs on game start, higher TECH score on recruit, and higher AM relations easy access to resources and vehicles EQ through missions and trade
**-Disadv:**
Tech Heresy: Less TMs and AM relations

**Comment by KRdaMystic** [comment]
This is something I thought of one day and would like some feedback or criticisms for it before I look into trying to design it.

**Comment by GalacticChimp** [comment]
duplicates #141
