### ISSUE TITLE
Bionics display crashing without the hash

### ISSUE THREAD

**Issue by renatosilvatimebel** [ZAB909/ChapterMaster#180]
I'm getting this error here in one of my playthroughs:

```
Unable to find instance for object index 0
 at gml_Script_scr_ui_manage (line 786) -  var_text = string_hash_to_newline(string("Bionics: {0}",selected_unit.bionics()))
############################################################################################
gml_Script_scr_ui_manage (line 786)
gml_Object_obj_controller_Draw_0 (line 17)
```

changing from this:
`string("Bionics: {0}",selected_unit.bionics())`
to this:
`string("Bionics: {0}#",selected_unit.bionics())`
fixed my crash.

**Comment by renatosilvatimebel** [comment]
nope, that didnt fixed at all...

**Comment by renatosilvatimebel** [comment]
ok let me give more context here, so i've created a custom chapter, the first turn when i try to browse a company, the first loaded marine comes empty so it crashes.

in this moment the `selected_unit` variable is coming out empty. I've added try/catches around all usages to see what was gonna happen in the UI.
![image](https://github.com/ZAB909/ChapterMaster/assets/69794358/5d37cbe1-a0ef-40f8-8a4b-3a78484b4a4b)

and this is what it was shown:
![image](https://github.com/ZAB909/ChapterMaster/assets/69794358/fc7c08fa-ea02-4895-8717-2a59d32627d3)

so it seems that it is not loading a default marine at that moment

**Comment by GalacticChimp** [comment]
@OH296, any ideas what could be causing this?

**Comment by GalacticChimp** [comment]
@renatosilvatimebel if this is fixed in dev version, then please close this issue
