### ISSUE TITLE
Can't bomb/attack a planet with enemies, only displays the Build button

### ISSUE THREAD

**Issue by renatosilvatimebel** [ZAB909/ChapterMaster#186]
**branch:** `main`
**checksum:** `93c4341d0`

Every now and then during the playthrough i've encountered planets that have enemy troops on the ground, but i cant seem to bomb or attack them, it only shows the Build button option in it. I do have my fleet with marines loaded so it should be a valid target.

Image 1 shows only the Build button and Image 2 shows another planet that has the attack option.

Planet 1:
![image](https://github.com/ZAB909/ChapterMaster/assets/69794358/4ff3f557-80da-40d1-a2c1-606391a8ece6)

Planet 2:
![image](https://github.com/ZAB909/ChapterMaster/assets/69794358/4a24cdb2-c901-4ee6-8aec-adcf844fe5fb)

**Comment by GalacticChimp** [comment]
@OH296 looks like a simple `if` issue?

**Comment by GalacticChimp** [comment]
@renatosilvatimebel please check if it works for you. If yes, please close this issue.

**Comment by renatosilvatimebel** [comment]
yup, all buttons working fine now.

thanks @OH296 and @GalacticChimp!

![image](https://github.com/ZAB909/ChapterMaster/assets/69794358/8e6890a1-3baa-4b04-8b00-b39c4a747009)
