### ISSUE TITLE
Custom role names not being displayed

### ISSUE THREAD

**Issue by KRdaMystic** [ZAB909/ChapterMaster#200]
Tech Marines, Terminators ,Dreadnoughts ,Honor Guards, Tactical ,and Assault Marines. These roles names will not change when changed on the chapter design screen

**Comment by GalacticChimp** [comment]
@OH296 any leads for this one?

**Comment by GalacticChimp** [comment]
assigning to 0.8.3.0 for now, if we decide to do a 0.8.2.2, then I'll reassign this
